---
# Xinyu Sun 952469
# Shiyu Dong 870480
# Jie Luo 1122592
# Yuxiang Xia 969367
# Yixuan Tang 959698
# pip install openstacksdk
- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
