---
# Xinyu Sun 952469
# Shiyu Dong 870480
# Jie Luo 1122592
# Yuxiang Xia 969367
# Yixuan Tang 959698
- name: Remove image
  become: yes
  docker_image:
    state: absent
    name: infinite12/webservice
    force: yes