---
# - name: deploy couchdb
#   hosts: all
#   roles:
#     - role: deploy-couchdb

# - name: set up couchDB cluster
#   hosts: leader
#   roles:
#     - role: cluster-setup

# - name: init docker swarm
#   hosts: leader
#   roles:
#     - role: deploy-swarm

# - name: Add manager
#   hosts: manager
#   roles:
#     - role: add-manager

# - name: Add worker
#   hosts: worker
#   roles:
#     - role: add-worker

# - name: Deploy tweets harvester
#   hosts: all
#   roles:
#     - role: deploy-harvester

- name: remove current web image
  hosts: all
  roles:
    - role: clean-web

- name: deploy web
  hosts: leader
  roles:
    - role: build-images
    - role: deploy-web