---
# Xinyu Sun 952469
# Shiyu Dong 870480
# Jie Luo 1122592
# Yuxiang Xia 969367
# Yixuan Tang 959698
- name: Leave swarm for a node
  become: yes
  docker_swarm:
    state: absent

- name: Add worker nodes
  become: yes
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars['node1']['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars['node1']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: ["{{ hostvars['node1']['ansible_default_ipv4']['address'] }}", "{{ hostvars['node2']['ansible_default_ipv4']['address'] }}"]