---
- name: remove container
  become: yes
  docker_container:
    name: couchDB
    state: absent

- name: create couchdb containers
  become: yes
  docker_container:
    name: couchDB
    image: couchdb
    state: started
    restart: yes
    volumes:
     - /home/ubuntu/couchdb/data:/opt/couchdb/data
    ports:
     - "5984:5984"
     - "4369:4369"
     - "9100-9200:9100-9200"
    env:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: password
        NODENAME: "{{ ansible_default_ipv4.address }}"