---
# Xinyu Sun 952469
# Shiyu Dong 870480
# Jie Luo 1122592
# Yuxiang Xia 969367
# Yixuan Tang 959698
- name: Remove a swarm manager
  become: yes
  docker_swarm:
    state: absent
    force: true

- name: Add manager nodes
  become: yes
  shell: |
    docker swarm join --token {{ hostvars['node1']['swarm_info']['swarm_facts']['JoinTokens']['Manager'] }} {{ hostvars['node1']['ansible_default_ipv4']['address'] }}:2377