---
- name: enable cluster
  become: yes
  loop: "{{ groups['nonLeader'] }}"
  shell: | 
      curl -X POST -H "Content-Type: application/json" http://admin:password@"{{ ansible_default_ipv4.address }}":5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 5984, "node_count": "{{ groups['all'] | length }}", "remote_node": "{{ hostvars[item]['ansible_ssh_host'] }}", "remote_current_user": "admin", "remote_current_password": "password" }'
      curl -X POST -H "Content-Type: application/json" http://admin:password@"{{ ansible_default_ipv4.address }}":5984/_cluster_setup -d '{"action": "add_node", "host":"{{ hostvars[item]['ansible_ssh_host'] }}", "port": 5984, "username": "admin", "password":"password"}'
 

- name: finish cluster
  become: yes
  shell: |
    curl -X POST -H "Content-Type: application/json" http://admin:password@"{{ ansible_default_ipv4.address }}":5984/_cluster_setup -d '{"action": "finish_cluster"}'

- name: add tweets database
  become: yes
  shell: |
    curl -X PUT "http://admin:password@"{{ ansible_default_ipv4.address }}":5984/tweets?q=4&n=2"
