---

- name: Change IP of couchDB in code
  become: yes
  lineinfile:
    path: /home/ubuntu/code/crawler/harvester_server.py
    regexp: '^couchdb_url='http://admin:admin@127.0.0.1:5984/''
    line: couchdb_url='http://admin:password@{{ ansible_default_ipv4.address }}:5984/'

- name: Build image
  become: yes
  docker_image:
    name: harvester_image
    build: 
      path: /home/ubuntu/code/crawler/
    source: build

- name: Run container  
  become: yes
  docker_container:
    name: tweets_harvester
    image: harvester_image
