---
# Xinyu Sun 952469
# Shiyu Dong 870480
# Jie Luo 1122592
# Yuxiang Xia 969367
# Yixuan Tang 959698
- name: remove container
  become: yes
  docker_container:
    name: tweets_harvester
    state: absent

- name: Copy file with owner and permissions
  copy:
    src: /Users/xinyusun/Desktop/ccc-ass2/crawler/twitter_credentials.py
    dest: /home/ubuntu/code/crawler/twitter_credentials.py

- name: Change key
  become: yes
  lineinfile:
    path: /home/ubuntu/code/crawler/harvester_server.py
    regexp: '^        key = twitter_credentials.keys\["ip"\]'
    line: '        key = twitter_credentials.keys["{{ ansible_default_ipv4.address }}"]'

- name: Change IP of couchDB in code
  become: yes
  lineinfile:
    path: /home/ubuntu/code/crawler/harvester_server.py
    regexp: '^        couchdb_url="http://admin:password@127.0.0.1:5984/"'
    line: '        couchdb_url="http://admin:password@{{ ansible_default_ipv4.address }}:5984/"'

- name: Remove image
  become: yes
  docker_image:
    state: absent
    name: harvester_image
    force: yes

- name: Build image
  become: yes
  docker_image:
    name: harvester_image
    build: 
      path: /home/ubuntu/code/crawler/
    source: build

- name: Run container  
  become: yes
  docker_container:
    name: tweets_harvester
    image: harvester_image
